# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.8.2.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - static-v3.8.2

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 4

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  APPVEYOR_RDP_PASSWORD: pass:1234

# scripts that are called at very beginning, before repo cloning
init:
  - echo init

  # clone directory
clone_folder: c:\cpython

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

cache:
  - externals

# scripts that run after cloning repository
install:

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: PCbuild/pcbuild.sln    # path to Visual Studio solution or project
  # MSBuild verbosity level
  verbosity: normal


# scripts to run before build
before_build:
  - C:\cpython\PCbuild\get_externals.bat
    --no-tkinter --no-openssl --no-libffi
    --tkinter-src --openssl-src --libffi-src
  - dir C:\cpython\externals
  - set VCVARSALL="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"
  - set CYG_BIN=C:\cygwin\bin
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - C:\cpython\PCbuild\prepare_libffi.bat -x64
  - C:\cpython\PCbuild\prepare_ssl.bat
  - C:\cpython\PCbuild\prepare_tcltk.bat
  - dir C:\cpython\externals

# to run your custom scripts instead of automatic MSBuild
build_script:

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - cd C:\cpython
  - C:\cygwin\bin\bash PCbuild/create_standalone_package.sh

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  - path: PCbuild/amd64/python.exe
  - path: PCbuild/amd64/python.pdb
  - path: PCbuild/standalone_dist/zip_libs.zip
